import { GlobalZipCode } from "../../../layout";
import React, { useContext } from "react";


export const southBeach = [{name:"Beach Day", image_url:"https://travel.home.sndimg.com/content/dam/images/travel/fullset/2015/12/04/south-beach-miami-florida.jpg.rend.hgtvcom.1280.960.suffix/1491581428208.jpeg", description:"Just beyond its iconic, pastel-hued Art Deco buildings lining Ocean Drive lies the area’s legendary shoreline with aquamarine water and fine sand. Famed for its cachet among international celebrities, South Beach is where you’ll find beautiful people soaking up the sun and the scene."},
{name:"South Pointe Park",image_url:"https://mywowo.net/media/images/cache/miami_south_pointe_park_01_presntazione_jpg_1200_630_cover_85.jpg", description:"South Pointe Park is a beautiful green space at the southern tip of Miami Beach. It offers stunning panoramic views of the South Beach shoreline."},
{name:"Sun Set Harbor",image_url:"https://media.tacdn.com/media/attractions-splice-spp-674x446/0c/0e/95/c4.jpg", description:"Best Spot to enjoy water activities such as Paddle boarding, jet skis and kayaking."},
{name:"Botanical Garden",image_url:"https://www.mbgarden.org/wp-content/uploads/2021/03/japanese7.jpg", description:"The Miami Beach Botanical Garden is a 2.6 acres urban green space with a $1.2 million landscape renovation designed by South Florida landscape architect Raymond Jungles."},
{name:"Lincoln Road Mall",image_url:"https://assets.simpleviewinc.com/simpleview/image/upload/c_fit,w_1440,h_900/crm/miamifl/180219LincolnRoad_KSPRA_080_401C1FE9-3CC8-4BDA-8F02A59088D3B36C_baeabf87-50b9-4911-ada98f3c5105e765.jpg", description:"Lincoln Road Mall is the premier shopping, dining, and entertainment destination in South Beach."},
{name:"New World Center",image_url:"https://images.adsttc.com/media/images/5007/303e/28ba/0d41/4800/14f4/newsletter/stringio.jpg", description:"The New World Center is a concert hall designed by Frank Gehry. It is the home of the New World Symphony, with a capacity of 756 seats"},
{name:"Nikki Beach",image_url:"https://images.miamiandbeaches.com/crm/simpleview/image/upload/c_fit,w_1440,h_900/crm/miamifl/Nikki-Beach-Miami-1-1440x9000-85e9f67a5056a36_85e9f7c0-5056-a36a-0b9b6adf3dd306b8.jpg", description:"Lounge the day away at Nikki Beach Miami Beach with outdoor seating, sunshine and fresh air! Beach loungers, daybeds and picture-perfect cabanas are available to reserve daily."},
{name:"Standard Spa",image_url:"https://res.cloudinary.com/lastminute/image/upload/c_scale,w_470/q_auto/v1646370172/d1y4cftox5hcauxxj5me.jpg", description:"Hydrotherapy playground that fosters stress-free socializing in a tropical, contemporary setting. With a minimalist design, the holistic hydrotherapy spa hotel provides a stylish yet intimate ambience just blocks from the glitz of South Beach."},
{name:"The Clevelander",image_url:"https://image-tc.galaxy.tf/wijpeg-3h5btl0ff7p219dmw8ohjip98/file.jpg", description:"Experience the energy of Miami like never before at Clevelander South Beach. Perched on Ocean Drive in the heart of the Art Deco District, our hotel is an icon on the Miami Beach scene."},
{name:"Beach Day", image_url:"https://travel.home.sndimg.com/content/dam/images/travel/fullset/2015/12/04/south-beach-miami-florida.jpg.rend.hgtvcom.1280.960.suffix/1491581428208.jpeg", description:"Just beyond its iconic, pastel-hued Art Deco buildings lining Ocean Drive lies the area’s legendary shoreline with aquamarine water and fine sand. Famed for its cachet among international celebrities, South Beach is where you’ll find beautiful people soaking up the sun and the scene."},
{name:"South Pointe Park",image_url:"https://mywowo.net/media/images/cache/miami_south_pointe_park_01_presntazione_jpg_1200_630_cover_85.jpg", description:"South Pointe Park is a beautiful green space at the southern tip of Miami Beach. It offers stunning panoramic views of the South Beach shoreline."},
{name:"Sun Set Harbor",image_url:"https://media.tacdn.com/media/attractions-splice-spp-674x446/0c/0e/95/c4.jpg", description:"Best Spot to enjoy water activities such as Paddle boarding, jet skis and kayaking."},
{name:"Botanical Garden",image_url:"https://www.mbgarden.org/wp-content/uploads/2021/03/japanese7.jpg", description:"The Miami Beach Botanical Garden is a 2.6 acres urban green space with a $1.2 million landscape renovation designed by South Florida landscape architect Raymond Jungles."},
{name:"Lincoln Road Mall",image_url:"https://assets.simpleviewinc.com/simpleview/image/upload/c_fit,w_1440,h_900/crm/miamifl/180219LincolnRoad_KSPRA_080_401C1FE9-3CC8-4BDA-8F02A59088D3B36C_baeabf87-50b9-4911-ada98f3c5105e765.jpg", description:"Lincoln Road Mall is the premier shopping, dining, and entertainment destination in South Beach."},
{name:"New World Center",image_url:"https://images.adsttc.com/media/images/5007/303e/28ba/0d41/4800/14f4/newsletter/stringio.jpg", description:"The New World Center is a concert hall designed by Frank Gehry. It is the home of the New World Symphony, with a capacity of 756 seats"},
{name:"Nikki Beach",image_url:"https://images.miamiandbeaches.com/crm/simpleview/image/upload/c_fit,w_1440,h_900/crm/miamifl/Nikki-Beach-Miami-1-1440x9000-85e9f67a5056a36_85e9f7c0-5056-a36a-0b9b6adf3dd306b8.jpg", description:"Lounge the day away at Nikki Beach Miami Beach with outdoor seating, sunshine and fresh air! Beach loungers, daybeds and picture-perfect cabanas are available to reserve daily."},
{name:"Standard Spa",image_url:"https://res.cloudinary.com/lastminute/image/upload/c_scale,w_470/q_auto/v1646370172/d1y4cftox5hcauxxj5me.jpg", description:"Hydrotherapy playground that fosters stress-free socializing in a tropical, contemporary setting. With a minimalist design, the holistic hydrotherapy spa hotel provides a stylish yet intimate ambience just blocks from the glitz of South Beach."},
{name:"The Clevelander",image_url:"https://image-tc.galaxy.tf/wijpeg-3h5btl0ff7p219dmw8ohjip98/file.jpg", description:"Experience the energy of Miami like never before at Clevelander South Beach. Perched on Ocean Drive in the heart of the Art Deco District, our hotel is an icon on the Miami Beach scene."},
{name:"Beach Day", image_url:"https://travel.home.sndimg.com/content/dam/images/travel/fullset/2015/12/04/south-beach-miami-florida.jpg.rend.hgtvcom.1280.960.suffix/1491581428208.jpeg", description:"Just beyond its iconic, pastel-hued Art Deco buildings lining Ocean Drive lies the area’s legendary shoreline with aquamarine water and fine sand. Famed for its cachet among international celebrities, South Beach is where you’ll find beautiful people soaking up the sun and the scene."},
{name:"South Pointe Park",image_url:"https://mywowo.net/media/images/cache/miami_south_pointe_park_01_presntazione_jpg_1200_630_cover_85.jpg", description:"South Pointe Park is a beautiful green space at the southern tip of Miami Beach. It offers stunning panoramic views of the South Beach shoreline."},
{name:"Sun Set Harbor",image_url:"https://media.tacdn.com/media/attractions-splice-spp-674x446/0c/0e/95/c4.jpg", description:"Best Spot to enjoy water activities such as Paddle boarding, jet skis and kayaking."},

];








export const wynwood = [ {name:"Wynwood Walls", image_url:"https://media2.miaminewtimes.com/mia/imager/u/original/11776034/wynwoodwalls8.jpeg", description:"Wynwood Walls has become a phenomenon, spurring the creation of murals throughout the Wynwood district. It is now one of the best venues in the world to see the work of leading street artists."},
{name:"Basel House",image_url:"https://www.wynwoodlife.com/wp-content/uploads/2018/12/baselsocial.jpg", description:"In the center of Miami's Wynwood Arts District, this FREE event will offer live painting, unique art installations, live music and late night DJ's"},
{name:"Museum of Graffiti",image_url:"https://static01.nyt.com/images/2019/12/05/arts/04graffiti-museum9/04graffiti-museum9-superJumbo.jpg", description:"The Museum of Graffiti exhibits, educates, and celebrates the thousands of graffiti artists who have transformed walls in our public spaces"},
{name:"Bicycle Pub Crawl",image_url:"https://img.grouponcdn.com/pwa_test/4EXb9Zkixbj743QwWDvz1hPC4VkX/4E-1440x810/v1/c870x524.jpg", description:"Miami's best mode of transportation takes you on a two-hour bar crawl to three bars in the Wynwood neighborhood. A souvenir cup is included"},
{name:"Mindie Film Fest",image_url:"https://s3.amazonaws.com/pbblogassets/uploads/2017/06/Theatrical-Screening.jpg", description:"Miami Film Festival showcases independent American and international films with a special focus on Ibero-American films."},
{name:"Brewing Company",image_url:"https://wynwoodbrewing.misystems.net/wp-content/uploads/2018/11/WBC2018-20.jpg", description:"Artsy area's first craft production brewery with a taproom pouring seasonal, limited-edition beers."},
{name:"Walk Wynwood",image_url:"https://i.pinimg.com/736x/37/be/43/37be4353a3e96056c50f890212ddb4c5--art-basel-art-centers.jpg", description:"Take a adventurous walk and view all the Street on of Wynwood canvased buildings "},
{name:"Lock & Load Miami",image_url:"https://img.grouponcdn.com/pwa_test/9p5Kxrnrf8QUxmL7ukNSGDHbDUP/9p-720x480/v1/sc600x600.jpg", description:"Experience the adrenaline rush of fully automatic firearms in a safe and private environment under the direct supervision of trained professionals."},
{name:"Selfie Museum",image_url:"https://mdcthereporter.com/wp-content/uploads/2021/01/Untitled-design13-800x445.jpg", description:"Original Selfie Museum is the first creative space uniquely designed to take your Photos and Videos to an entirely new level of Awesomeness."},
{name:"Wynwood Walls", image_url:"https://media2.miaminewtimes.com/mia/imager/u/original/11776034/wynwoodwalls8.jpeg", description:"Wynwood Walls has become a phenomenon, spurring the creation of murals throughout the Wynwood district. It is now one of the best venues in the world to see the work of leading street artists."},
{name:"Basel House",image_url:"https://www.wynwoodlife.com/wp-content/uploads/2018/12/baselsocial.jpg", description:"In the center of Miami's Wynwood Arts District, this FREE event will offer live painting, unique art installations, live music and late night DJ's"},
{name:"Museum of Graffiti",image_url:"https://static01.nyt.com/images/2019/12/05/arts/04graffiti-museum9/04graffiti-museum9-superJumbo.jpg", description:"The Museum of Graffiti exhibits, educates, and celebrates the thousands of graffiti artists who have transformed walls in our public spaces"},
{name:"Bicycle Pub Crawl",image_url:"https://img.grouponcdn.com/pwa_test/4EXb9Zkixbj743QwWDvz1hPC4VkX/4E-1440x810/v1/c870x524.jpg", description:"Miami's best mode of transportation takes you on a two-hour bar crawl to three bars in the Wynwood neighborhood. A souvenir cup is included"},
{name:"Mindie Film Fest",image_url:"https://s3.amazonaws.com/pbblogassets/uploads/2017/06/Theatrical-Screening.jpg", description:"Miami Film Festival showcases independent American and international films with a special focus on Ibero-American films."},
{name:"Brewing Company",image_url:"https://wynwoodbrewing.misystems.net/wp-content/uploads/2018/11/WBC2018-20.jpg", description:"Artsy area's first craft production brewery with a taproom pouring seasonal, limited-edition beers."},
{name:"Walk Wynwood",image_url:"https://i.pinimg.com/736x/37/be/43/37be4353a3e96056c50f890212ddb4c5--art-basel-art-centers.jpg", description:"Take a adventurous walk and view all the Street on of Wynwood canvased buildings "},
{name:"Lock & Load Miami",image_url:"https://img.grouponcdn.com/pwa_test/9p5Kxrnrf8QUxmL7ukNSGDHbDUP/9p-720x480/v1/sc600x600.jpg", description:"Experience the adrenaline rush of fully automatic firearms in a safe and private environment under the direct supervision of trained professionals."},
{name:"Selfie Museum",image_url:"https://mdcthereporter.com/wp-content/uploads/2021/01/Untitled-design13-800x445.jpg", description:"Original Selfie Museum is the first creative space uniquely designed to take your Photos and Videos to an entirely new level of Awesomeness."},
{name:"Wynwood Walls", image_url:"https://media2.miaminewtimes.com/mia/imager/u/original/11776034/wynwoodwalls8.jpeg", description:"Wynwood Walls has become a phenomenon, spurring the creation of murals throughout the Wynwood district. It is now one of the best venues in the world to see the work of leading street artists."},
{name:"Basel House",image_url:"https://www.wynwoodlife.com/wp-content/uploads/2018/12/baselsocial.jpg", description:"In the center of Miami's Wynwood Arts District, this FREE event will offer live painting, unique art installations, live music and late night DJ's"},
{name:"Museum of Graffiti",image_url:"https://static01.nyt.com/images/2019/12/05/arts/04graffiti-museum9/04graffiti-museum9-superJumbo.jpg", description:"The Museum of Graffiti exhibits, educates, and celebrates the thousands of graffiti artists who have transformed walls in our public spaces"},
];









export const doral= [{name:"CineBistro", image_url:"https://media.timeout.com/images/101506367/image.jpg", description:"Best Movie theater in Doral come to the City Center to Watch Next Blockbuster Hit"},
{name:"Improv",image_url:"https://i0.wp.com/miamicomedy.com/wp-content/uploads/2019/11/Screen-Shot-2019-09-15-at-2.46.39-PM-scaled.png", description:"Relaxed, brick-clad venue dishing out improv comedy plus American comfort fare, beer & cocktails."},
{name:"Kings Entertainment",image_url:"https://media1.miaminewtimes.com/mia/imager/u/golden-m/14721905/screen_shot_2017-05-10_at_4.35.41_pm.png", description:"Bowling, Pool and More! Award-winning gathering place for people to connect, play, eat, drink and laugh together"},
{name:"Top Golf",image_url:"https://media.phillyvoice.com/media/images/05_17_2022_Topgolf_Northeast_Philly.width-696.jpg", description:"Premier entertainment venues featuring fun golf games for all skill levels, full-service bar and restaurant"},
{name:"Launch Trampoline",image_url:"https://ap3j6r9z7q4a4hq7uks386he-wpengine.netdna-ssl.com/wp-content/uploads/2018/10/Battle-Beam-IMG_3570.jpg", description:"Launch Trampoline Park is endless indoor entertainment for kids and adults"},
{name:"Warrior Gun Range",image_url:"https://cdn7.coreware.com/cache/image-full-145676-0522af39bb21bd385365a3ce961ee1fa.jpg", description:"Warrior Gun Range and Shop is Doral's #1 indoor shooting range with excellent service and many styles of guns available"},
{name:"Laelanie Art Gallery",image_url:"https://pbs.twimg.com/media/FBAp5h6VEAUL7Jf.jpg", description:"A unique art gallery owned by the artist Laelanie Larach in Miami Florida. Laelanie Art Gallery only sells original oil paintings and modern art of the artist Laelanie Larach."},
{name:"Spa Azul",image_url:"https://img.grouponcdn.com/deal/3Ezd5VDVivKFN4f6FVWkxmETyenm/3E-1150x690/v1/c870x524.jpg", description:"Spa Azul at The Blue Miami Situated on 17 acres of lush landscape peppered with palm trees, Spa Azul at The Blue Miami offers a wealth of indulgent treatments."},
{name:"Doral Central Park",image_url:"https://res.cloudinary.com/dpqp2pvqp/image/upload/v1619436653/DCP-Slide-1_trvvdz.jpg", description:"This 82-acre park is the largest park in the City and home to major events"},
{name:"CineBistro", image_url:"https://media.timeout.com/images/101506367/image.jpg", description:"Best Movie theater in Doral come to the City Center to Watch Next Blockbuster Hit"},
{name:"Improv",image_url:"https://i0.wp.com/miamicomedy.com/wp-content/uploads/2019/11/Screen-Shot-2019-09-15-at-2.46.39-PM-scaled.png", description:"Relaxed, brick-clad venue dishing out improv comedy plus American comfort fare, beer & cocktails."},
{name:"Kings Entertainment",image_url:"https://media1.miaminewtimes.com/mia/imager/u/golden-m/14721905/screen_shot_2017-05-10_at_4.35.41_pm.png", description:"Bowling, Pool and More! Award-winning gathering place for people to connect, play, eat, drink and laugh together"},
{name:"Top Golf",image_url:"https://media.phillyvoice.com/media/images/05_17_2022_Topgolf_Northeast_Philly.width-696.jpg", description:"Premier entertainment venues featuring fun golf games for all skill levels, full-service bar and restaurant"},
{name:"Launch Trampoline",image_url:"https://ap3j6r9z7q4a4hq7uks386he-wpengine.netdna-ssl.com/wp-content/uploads/2018/10/Battle-Beam-IMG_3570.jpg", description:"Launch Trampoline Park is endless indoor entertainment for kids and adults"},
{name:"Warrior Gun Range",image_url:"https://cdn7.coreware.com/cache/image-full-145676-0522af39bb21bd385365a3ce961ee1fa.jpg", description:"Warrior Gun Range and Shop is Doral's #1 indoor shooting range with excellent service and many styles of guns available"},
{name:"Laelanie Art Gallery",image_url:"https://pbs.twimg.com/media/FBAp5h6VEAUL7Jf.jpg", description:"A unique art gallery owned by the artist Laelanie Larach in Miami Florida. Laelanie Art Gallery only sells original oil paintings and modern art of the artist Laelanie Larach."},
{name:"Spa Azul",image_url:"https://img.grouponcdn.com/deal/3Ezd5VDVivKFN4f6FVWkxmETyenm/3E-1150x690/v1/c870x524.jpg", description:"Spa Azul at The Blue Miami Situated on 17 acres of lush landscape peppered with palm trees, Spa Azul at The Blue Miami offers a wealth of indulgent treatments."},
{name:"Doral Central Park",image_url:"https://res.cloudinary.com/dpqp2pvqp/image/upload/v1619436653/DCP-Slide-1_trvvdz.jpg", description:"This 82-acre park is the largest park in the City and home to major events"},
{name:"CineBistro", image_url:"https://media.timeout.com/images/101506367/image.jpg", description:"Best Movie theater in Doral come to the City Center to Watch Next Blockbuster Hit"},
{name:"Improv",image_url:"https://i0.wp.com/miamicomedy.com/wp-content/uploads/2019/11/Screen-Shot-2019-09-15-at-2.46.39-PM-scaled.png", description:"Relaxed, brick-clad venue dishing out improv comedy plus American comfort fare, beer & cocktails."},
{name:"Kings Entertainment",image_url:"https://media1.miaminewtimes.com/mia/imager/u/golden-m/14721905/screen_shot_2017-05-10_at_4.35.41_pm.png", description:"Bowling, Pool and More! Award-winning gathering place for people to connect, play, eat, drink and laugh together"}

];





export const brickell = [{name:"City Centre", image_url:"https://www.newlink-group.com/uploads/press/f10ff50024f73005a20b979626949c9a53a2664d.jpg", description:"One of the most stylish shopping spots in Miami. Brickell City Centre has three to four levels of excellent shopping, dining and entertainment"},
{name:"FTX arena", image_url:"https://genesisblockhk.com/wp-content/uploads/2021/06/4uLHD0YA.jpg", description:"Located in Downtown Miami. Come for Concerts, Sporting Events, and More! "},
{name:"Bayside MarketPlace", image_url:"https://www.miamigov.com/files/sharedassets/public/dream/marinas/miamarina-bayside-4.jpg", description:"Bayside Marketplace is a two-story open air shopping center located in the downtown Miami, Florida. The banks of Biscayne Bay wrap around the property with the City of Miami marina at its side."},
{name:"Jungle Island",image_url:" https://travelpedia.com.br/wp-content/uploads/2017/05/jungle-island-miami-1-770x428.png", description:"Jungle Island, formerly Parrot Jungle, is a relaunched eco-adventure park on Watson Island, Miami, Florida, United States."},
{name:"Frost Science Museum",image_url:"https://i.ytimg.com/vi/kLx55YsWo1k/maxresdefault.jpg", description:"Frost Science is a leading science museum dedicated to sharing the power of science, sparking wonder and investigation"},
{name:"Perez Art Museum",image_url:"https://seele.com/fileadmin/user_upload/images/01_References/Perez_Art_Museum/PerezArtMuseum_c_Armandov__2_.jpg", description:"Pérez Art Museum Miami is a modern and contemporary art museum dedicated to collecting and exhibiting international art of the 20th and 21st centuries."},
{name:"Bloom Skybar",image_url:"https://media-cdn.tripadvisor.com/media/photo-s/12/85/86/65/bloom-skybar.jpg", description:" Bloom Skybar is a fantastic Miami rooftop bar for a fun downtown-night out with friends, enjoying the casual-chic vibes"},
{name:"Axe throwing",image_url:"https://images.miamiandbeaches.com/crm/simpleview/image/upload/c_fit,w_1440,h_900/crm/miamifl/Extreme-Axe-Throwing-1440x9000-a3cc8d815056a36_a3cc8f6b-5056-a36a-0bda2ed5b6203d60.jpg", description:"Miami's first indoor axe throwing experience offering competitive and recreational interactive targets."},
{name:"Eleven",image_url:"https://i.ytimg.com/vi/c4KB7aHv-fg/maxresdefault.jpg", description:"Miami's #1 nightlife destination, featuring top DJs, Live Music, a Full Menu and Sexy Performers 24/7!"},
{name:"City Centre", image_url:"https://www.newlink-group.com/uploads/press/f10ff50024f73005a20b979626949c9a53a2664d.jpg", description:"One of the most stylish shopping spots in Miami. Brickell City Centre has three to four levels of excellent shopping, dining and entertainment"},
{name:"FTX arena", image_url:"https://genesisblockhk.com/wp-content/uploads/2021/06/4uLHD0YA.jpg", description:"Located in Downtown Miami. Come for Concerts, Sporting Events, and More! "},
{name:"Bayside MarketPlace", image_url:"https://www.miamigov.com/files/sharedassets/public/dream/marinas/miamarina-bayside-4.jpg", description:"Bayside Marketplace is a two-story open air shopping center located in the downtown Miami, Florida. The banks of Biscayne Bay wrap around the property with the City of Miami marina at its side."},
{name:"Jungle Island",image_url:" https://travelpedia.com.br/wp-content/uploads/2017/05/jungle-island-miami-1-770x428.png", description:"Jungle Island, formerly Parrot Jungle, is a relaunched eco-adventure park on Watson Island, Miami, Florida, United States."},
{name:"Frost Science Museum",image_url:"https://i.ytimg.com/vi/kLx55YsWo1k/maxresdefault.jpg", description:"Frost Science is a leading science museum dedicated to sharing the power of science, sparking wonder and investigation"},
{name:"Perez Art Museum",image_url:"https://seele.com/fileadmin/user_upload/images/01_References/Perez_Art_Museum/PerezArtMuseum_c_Armandov__2_.jpg", description:"Pérez Art Museum Miami is a modern and contemporary art museum dedicated to collecting and exhibiting international art of the 20th and 21st centuries."},
{name:"Bloom Skybar",image_url:"https://media-cdn.tripadvisor.com/media/photo-s/12/85/86/65/bloom-skybar.jpg", description:" Bloom Skybar is a fantastic Miami rooftop bar for a fun downtown-night out with friends, enjoying the casual-chic vibes"},
{name:"Axe throwing",image_url:"https://images.miamiandbeaches.com/crm/simpleview/image/upload/c_fit,w_1440,h_900/crm/miamifl/Extreme-Axe-Throwing-1440x9000-a3cc8d815056a36_a3cc8f6b-5056-a36a-0bda2ed5b6203d60.jpg", description:"Miami's first indoor axe throwing experience offering competitive and recreational interactive targets."},
{name:"Eleven",image_url:"https://i.ytimg.com/vi/c4KB7aHv-fg/maxresdefault.jpg", description:"Miami's #1 nightlife destination, featuring top DJs, Live Music, a Full Menu and Sexy Performers 24/7!"},
{name:"City Centre", image_url:"https://www.newlink-group.com/uploads/press/f10ff50024f73005a20b979626949c9a53a2664d.jpg", description:"One of the most stylish shopping spots in Miami. Brickell City Centre has three to four levels of excellent shopping, dining and entertainment"},
{name:"FTX arena", image_url:"https://genesisblockhk.com/wp-content/uploads/2021/06/4uLHD0YA.jpg", description:"Located in Downtown Miami. Come for Concerts, Sporting Events, and More! "},
{name:"Bayside MarketPlace", image_url:"https://www.miamigov.com/files/sharedassets/public/dream/marinas/miamarina-bayside-4.jpg", description:"Bayside Marketplace is a two-story open air shopping center located in the downtown Miami, Florida. The banks of Biscayne Bay wrap around the property with the City of Miami marina at its side."},
];



 //NYC activities by location 
 export const upperEastSide = [{name:"Central Park",image_url:"https://mymodernmet.com/wp/wp-content/uploads/2020/12/central-park-new-york-city-frederick-law-olmsted-thumbnail-4.png", description:"Central Park is an urban park in New York City, between the Upper West and Upper East Sides of Manhattan."},
 {name:"Acquavella",image_url:"https://s3.amazonaws.com/files.collageplatform.com.prod/image_cache/800x545/559650f9cfaf34ff158b4568/7f8ff106a85473ca87d913ec3985bd4f.jpeg", description:"Acquavella Galleries is an art gallery located at 18 East 79th Street between Madison and Fifth Avenues"},
 {name:"Neue Galerie",image_url:"https://i0.wp.com/www.architect-us.com/blog/wp-content/uploads/2018/04/32237871_640980912913332_23249761779843072_n.jpg", description:"The Neue Galerie New York is a museum of early twentieth-century German and Austrian art and design located in the William Starr Miller House at 86th Street and Fifth Avenue"},
 {name:"Smithsonian Design Museum",image_url:"https://www.loringengineers.com/wp/wp-content/uploads/2017/06/5190F.jpg", description:"Cooper Hewitt, Smithsonian Design Museum is a design museum located in the Upper East Side's Museum Mile"},
 {name:"The Frick Collection",image_url:"https://abigailkirsch.com/wp-content/uploads/2020/12/Frick-1-400x400.jpg", description:"The Frick Collection permanent collection features Old Master paintings and European fine and decorative arts, including works by Bellini, Fragonard, Goya, Rembrandt, Turner, Velázquez, Vermeer, and many others."},
 {name:"Guggenheim Museum",image_url:"https://gotourismguides.com/nyc/wp-content/uploads/nyc-guggenheim-museum.jpg", description:"Committed to innovation, the Solomon R. Guggenheim Foundation collects, preserves, and interprets modern and contemporary art, and explores ideas across cultures through dynamic curatorial and educational initiatives and collaborations."},
 {name:"Park Avenue Armory",image_url:"https://static01.nyt.com/images/2019/01/15/arts/22armory-still/merlin_148366617_fd6f205d-a4ff-4fee-87b7-2ae76b3d4aec-superJumbo.jpg", description:"Part palace, part industrial shed, Park Avenue Armory fills a critical void in the cultural ecology of New York, supporting unconventional works in the performing and visual arts that cannot be fully realized in a traditional proscenium theater, concert hall, or white wall gallery."},
 {name:" NY Society Library",image_url:"https://i.pinimg.com/736x/85/41/56/85415619db1dc8eab6917cd5bf55f3a8.jpg", description:"Our first-floor reading room, exhibitions, and many events are open to the public."},
 {name:"John Jay Park",image_url:"https://sideways.nyc/wp-content/uploads/2015/12/E-78th-Street-John-Jay-Park-TA02.jpg", description:"Whether you want to play basketball, swim a lap, or take a walk in wonderful community setting, John Jay Park & Pool is the place to be. With such impressive facilities, it is no surprise that it's packed with families year-round."},
 {name:"Central Park",image_url:"https://mymodernmet.com/wp/wp-content/uploads/2020/12/central-park-new-york-city-frederick-law-olmsted-thumbnail-4.png", description:"Central Park is an urban park in New York City, between the Upper West and Upper East Sides of Manhattan."},
 {name:"Acquavella",image_url:"https://s3.amazonaws.com/files.collageplatform.com.prod/image_cache/800x545/559650f9cfaf34ff158b4568/7f8ff106a85473ca87d913ec3985bd4f.jpeg", description:"Acquavella Galleries is an art gallery located at 18 East 79th Street between Madison and Fifth Avenues"},
 {name:"Neue Galerie",image_url:"https://i0.wp.com/www.architect-us.com/blog/wp-content/uploads/2018/04/32237871_640980912913332_23249761779843072_n.jpg", description:"The Neue Galerie New York is a museum of early twentieth-century German and Austrian art and design located in the William Starr Miller House at 86th Street and Fifth Avenue"},
 {name:"Smithsonian Design Museum",image_url:"https://www.loringengineers.com/wp/wp-content/uploads/2017/06/5190F.jpg", description:"Cooper Hewitt, Smithsonian Design Museum is a design museum located in the Upper East Side's Museum Mile"},
 {name:"The Frick Collection",image_url:"https://abigailkirsch.com/wp-content/uploads/2020/12/Frick-1-400x400.jpg", description:"The Frick Collection permanent collection features Old Master paintings and European fine and decorative arts, including works by Bellini, Fragonard, Goya, Rembrandt, Turner, Velázquez, Vermeer, and many others."},
 {name:"Guggenheim Museum",image_url:"https://gotourismguides.com/nyc/wp-content/uploads/nyc-guggenheim-museum.jpg", description:"Committed to innovation, the Solomon R. Guggenheim Foundation collects, preserves, and interprets modern and contemporary art, and explores ideas across cultures through dynamic curatorial and educational initiatives and collaborations."},
 {name:"Park Avenue Armory",image_url:"https://static01.nyt.com/images/2019/01/15/arts/22armory-still/merlin_148366617_fd6f205d-a4ff-4fee-87b7-2ae76b3d4aec-superJumbo.jpg", description:"Part palace, part industrial shed, Park Avenue Armory fills a critical void in the cultural ecology of New York, supporting unconventional works in the performing and visual arts that cannot be fully realized in a traditional proscenium theater, concert hall, or white wall gallery."},
 {name:" NY Society Library",image_url:"https://i.pinimg.com/736x/85/41/56/85415619db1dc8eab6917cd5bf55f3a8.jpg", description:"Our first-floor reading room, exhibitions, and many events are open to the public."},
 {name:"John Jay Park",image_url:"https://sideways.nyc/wp-content/uploads/2015/12/E-78th-Street-John-Jay-Park-TA02.jpg", description:"Whether you want to play basketball, swim a lap, or take a walk in wonderful community setting, John Jay Park & Pool is the place to be. With such impressive facilities, it is no surprise that it's packed with families year-round."},
 {name:"Central Park",image_url:"https://mymodernmet.com/wp/wp-content/uploads/2020/12/central-park-new-york-city-frederick-law-olmsted-thumbnail-4.png", description:"Central Park is an urban park in New York City, between the Upper West and Upper East Sides of Manhattan."},
 {name:"Acquavella",image_url:"https://s3.amazonaws.com/files.collageplatform.com.prod/image_cache/800x545/559650f9cfaf34ff158b4568/7f8ff106a85473ca87d913ec3985bd4f.jpeg", description:"Acquavella Galleries is an art gallery located at 18 East 79th Street between Madison and Fifth Avenues"},
 {name:"Neue Galerie",image_url:"https://i0.wp.com/www.architect-us.com/blog/wp-content/uploads/2018/04/32237871_640980912913332_23249761779843072_n.jpg", description:"The Neue Galerie New York is a museum of early twentieth-century German and Austrian art and design located in the William Starr Miller House at 86th Street and Fifth Avenue"}
 
];

 export const soho = [{name:"Blue Note Jazz Club",image_url:"https://cloudinary-assets.dostuffmedia.com/res/dostuff-media/image/upload/event-1755176/1425858988.jpg", description:"Legendary jazz musicians take the stage at this intimate club that also serves American eats."},
 {name:"Comedy Cellar",image_url:"https://assets.website-files.com/5d537d1201f72a56d4fd8c96/5d5ca0e60a3fc91eb53368dd_image-1.jpg", description:"The Comedy Cellar is a comedy club in Manhattan where many top New York comedians perform. It is widely considered to be the best comedy club in the country. "},
 {name:"Bleeker Street",image_url:"https://i.pinimg.com/originals/ba/62/4b/ba624bead403043b77ca9cc91dbac8e9.jpg", description:"One of the most famous streets in the city with great restaurants, bars, cafes, shopping stores, and clubs to see and explore!"},
 {name:"Friends Apartment",image_url:"https://www.cheatsheet.com/wp-content/uploads/2019/07/Friends-apartment-1024x668.jpg", description:"It's located at 90 Bedford Street at the corner of Grove Street. Reaching the building used for the exterior shot of the Friends apartment"},
 {name:"Christopher Street",image_url:"https://media.villagepreservation.org/wp-content/uploads/2020/05/15041609/christopherpark.jpg", description:" It is the continuation of 9th Street west of Sixth Avenue. It is most notable for the Stonewall Inn, which is located on Christopher Street near the corner of Seventh Avenue"},
 {name:" Village Vanguard",image_url:"https://i.pinimg.com/originals/85/d5/55/85d555b18a89cb5f956c4fedf8d47f69.jpg", description:"From iconic 1960s gigs by John Coltrane to who's playing here now, this club lives up to its name."},
 {name:"Stonewall National Monument",image_url:"https://2traveldads.com/wp-content/uploads/Stonewall-National-Monument-from-NPS-site-2.jpg", description:"Stonewall National Monument is a 7.7-acre U.S. National Monument in the West Village neighborhood"},
 {name:"Washington Square Park",image_url:"https://en.wikipedia.org/wiki/Washington_Square_Park#/media/File:Washington_Square_Arch-Isabella.jpg", description:"Washington Square Park is a 9.75-acre public park in the Greenwich Village neighborhood of Lower Manhattan, New York City. One of the best known of New York City's public parks, it is an icon as well as a meeting place and center for cultural activity"},
 {name:"Whitney Museum of American Art",image_url:"https://en.wikipedia.org/wiki/Whitney_Museum#/media/File:Whitney_Museum_of_American_Art_(49051573133).jpg", description:"The Whitney Museum of American Art, known informally as The Whitney, is an art museum in the Meatpacking District and West Village neighborhoods of Manhattan in New York City"},
 {name:"Blue Note Jazz Club",image_url:"https://cloudinary-assets.dostuffmedia.com/res/dostuff-media/image/upload/event-1755176/1425858988.jpg", description:"Legendary jazz musicians take the stage at this intimate club that also serves American eats."},
 {name:"Comedy Cellar",image_url:"https://assets.website-files.com/5d537d1201f72a56d4fd8c96/5d5ca0e60a3fc91eb53368dd_image-1.jpg", description:"The Comedy Cellar is a comedy club in Manhattan where many top New York comedians perform. It is widely considered to be the best comedy club in the country. "},
 {name:"Bleeker Street",image_url:"https://i.pinimg.com/originals/ba/62/4b/ba624bead403043b77ca9cc91dbac8e9.jpg", description:"One of the most famous streets in the city with great restaurants, bars, cafes, shopping stores, and clubs to see and explore!"},
 {name:"Friends Apartment",image_url:"https://www.cheatsheet.com/wp-content/uploads/2019/07/Friends-apartment-1024x668.jpg", description:"It's located at 90 Bedford Street at the corner of Grove Street. Reaching the building used for the exterior shot of the Friends apartment"},
 {name:"Christopher Street",image_url:"https://media.villagepreservation.org/wp-content/uploads/2020/05/15041609/christopherpark.jpg", description:" It is the continuation of 9th Street west of Sixth Avenue. It is most notable for the Stonewall Inn, which is located on Christopher Street near the corner of Seventh Avenue"},
 {name:" Village Vanguard",image_url:"https://i.pinimg.com/originals/85/d5/55/85d555b18a89cb5f956c4fedf8d47f69.jpg", description:"From iconic 1960s gigs by John Coltrane to who's playing here now, this club lives up to its name."},
 {name:"Stonewall National Monument",image_url:"https://2traveldads.com/wp-content/uploads/Stonewall-National-Monument-from-NPS-site-2.jpg", description:"Stonewall National Monument is a 7.7-acre U.S. National Monument in the West Village neighborhood"},
 {name:"Washington Square Park",image_url:"https://en.wikipedia.org/wiki/Washington_Square_Park#/media/File:Washington_Square_Arch-Isabella.jpg", description:"Washington Square Park is a 9.75-acre public park in the Greenwich Village neighborhood of Lower Manhattan, New York City. One of the best known of New York City's public parks, it is an icon as well as a meeting place and center for cultural activity"},
 {name:"Whitney Museum of American Art",image_url:"https://en.wikipedia.org/wiki/Whitney_Museum#/media/File:Whitney_Museum_of_American_Art_(49051573133).jpg", description:"The Whitney Museum of American Art, known informally as The Whitney, is an art museum in the Meatpacking District and West Village neighborhoods of Manhattan in New York City"},
 {name:"Comedy Cellar",image_url:"https://assets.website-files.com/5d537d1201f72a56d4fd8c96/5d5ca0e60a3fc91eb53368dd_image-1.jpg", description:"The Comedy Cellar is a comedy club in Manhattan where many top New York comedians perform. It is widely considered to be the best comedy club in the country. "}

];

 export const brooklyn= [{name:"Coney Island",image_url:"https://en.wikipedia.org/wiki/Coney_Island#/media/File:Coney_Island_beach_and_amusement_parks_(June_2016).jpg", description:"Coney Island is a peninsular neighborhood and entertainment area in the southwestern section of the New York City borough of Brooklyn"},
 {name:"Brooklyn Botanic Garden",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Botanic_Garden#/media/File:Bridge_to_Eden.jpg", description:"Brooklyn Botanic Garden is a botanical garden in the borough of Brooklyn, New York City. It was founded in 1910 using land from Mount Prospect Park in central Brooklyn"},
 {name:"New York Aquarium",image_url:"https://en.wikipedia.org/wiki/New_York_Aquarium#/media/File:New_York_Aquarium_by_David_Shankbone.jpg", description:"The New York Aquarium is the oldest continually operating aquarium in the United States, located on the Riegelmann Boardwalk in Coney Island, Brooklyn, New York City"},
 {name:"Brooklyn Museum",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Museum#/media/File:Brooklyn_Museum_Night_2015.jpg", description:"At 560,000 square feet, the museum is New York City's third largest in physical size and holds an art collection with roughly 500,000 objects."},
 {name:"Brooklyn Bridge Park",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Bridge_Park#/media/File:View_of_Brooklyn_Bridge_Park_from_Manhattan_Bridge.jpg", description:"Brooklyn Bridge Park is an 85-acre park on the Brooklyn side of the East River in New York City. Designed by landscape architecture firm Michael Van Valkenburgh Associates."},
 {name:"Barclays Center",image_url:" https://en.wikipedia.org/wiki/Barclays_Center#/media/File:BarclayCenter-2_(48034233762).jpg", description:"The arena is home to the Brooklyn Nets. The arena also hosts concerts, conventions and other sporting and entertainment events."},
 {name:"Brooklyn Heights Promenade",image_url:"https://www.iloveny360.com/wp-content/uploads/2015/09/brooklyn_parc-1024x536.jpg", description:"The Brooklyn Heights Promenade, also called the Esplanade, is a 1,826-foot-long platform and pedestrian walkway cantilevered over the Brooklyn-Queens Expressway"},
 {name:"New York Transit Museum",image_url:"https://en.wikipedia.org/wiki/New_York_Transit_Museum#/media/File:The_Squirrels_0043.jpg", description:"The New York Transit Museum is a museum that displays historical artifacts of the New York City Subway, bus, and commuter rail systems in the greater New York City metropolitan region"},
 {name:"Prospect Park",image_url:"https://www.nycgo.com/images/venues/73/prospectpark_schaer-008_2__large.jpg", description:"Prospect Park is an urban park in Brooklyn, New York City. The park is situated between the neighborhoods of Park Slope, Prospect Heights, Prospect Lefferts Gardens."},
 {name:"Coney Island",image_url:"https://en.wikipedia.org/wiki/Coney_Island#/media/File:Coney_Island_beach_and_amusement_parks_(June_2016).jpg", description:"Coney Island is a peninsular neighborhood and entertainment area in the southwestern section of the New York City borough of Brooklyn"},
 {name:"Brooklyn Botanic Garden",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Botanic_Garden#/media/File:Bridge_to_Eden.jpg", description:"Brooklyn Botanic Garden is a botanical garden in the borough of Brooklyn, New York City. It was founded in 1910 using land from Mount Prospect Park in central Brooklyn"},
 {name:"New York Aquarium",image_url:"https://en.wikipedia.org/wiki/New_York_Aquarium#/media/File:New_York_Aquarium_by_David_Shankbone.jpg", description:"The New York Aquarium is the oldest continually operating aquarium in the United States, located on the Riegelmann Boardwalk in Coney Island, Brooklyn, New York City"},
 {name:"Brooklyn Museum",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Museum#/media/File:Brooklyn_Museum_Night_2015.jpg", description:"At 560,000 square feet, the museum is New York City's third largest in physical size and holds an art collection with roughly 500,000 objects."},
 {name:"Brooklyn Bridge Park",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Bridge_Park#/media/File:View_of_Brooklyn_Bridge_Park_from_Manhattan_Bridge.jpg", description:"Brooklyn Bridge Park is an 85-acre park on the Brooklyn side of the East River in New York City. Designed by landscape architecture firm Michael Van Valkenburgh Associates."},
 {name:"Barclays Center",image_url:" https://en.wikipedia.org/wiki/Barclays_Center#/media/File:BarclayCenter-2_(48034233762).jpg", description:"The arena is home to the Brooklyn Nets. The arena also hosts concerts, conventions and other sporting and entertainment events."},
 {name:"Brooklyn Heights Promenade",image_url:"https://www.iloveny360.com/wp-content/uploads/2015/09/brooklyn_parc-1024x536.jpg", description:"The Brooklyn Heights Promenade, also called the Esplanade, is a 1,826-foot-long platform and pedestrian walkway cantilevered over the Brooklyn-Queens Expressway"},
 {name:"New York Transit Museum",image_url:"https://en.wikipedia.org/wiki/New_York_Transit_Museum#/media/File:The_Squirrels_0043.jpg", description:"The New York Transit Museum is a museum that displays historical artifacts of the New York City Subway, bus, and commuter rail systems in the greater New York City metropolitan region"},
 {name:"Prospect Park",image_url:"https://www.nycgo.com/images/venues/73/prospectpark_schaer-008_2__large.jpg", description:"Prospect Park is an urban park in Brooklyn, New York City. The park is situated between the neighborhoods of Park Slope, Prospect Heights, Prospect Lefferts Gardens."},
 {name:"Coney Island",image_url:"https://en.wikipedia.org/wiki/Coney_Island#/media/File:Coney_Island_beach_and_amusement_parks_(June_2016).jpg", description:"Coney Island is a peninsular neighborhood and entertainment area in the southwestern section of the New York City borough of Brooklyn"},
 {name:"Brooklyn Botanic Garden",image_url:"https://en.wikipedia.org/wiki/Brooklyn_Botanic_Garden#/media/File:Bridge_to_Eden.jpg", description:"Brooklyn Botanic Garden is a botanical garden in the borough of Brooklyn, New York City. It was founded in 1910 using land from Mount Prospect Park in central Brooklyn"},
 {name:"New York Aquarium",image_url:"https://en.wikipedia.org/wiki/New_York_Aquarium#/media/File:New_York_Aquarium_by_David_Shankbone.jpg", description:"The New York Aquarium is the oldest continually operating aquarium in the United States, located on the Riegelmann Boardwalk in Coney Island, Brooklyn, New York City"}
 
];

 export const financial = [{name:"National September 11 Memorial",image_url:"https://en.wikipedia.org/wiki/National_September_11_Memorial_%26_Museum#/media/File:9-11_Memorial_and_Museum_(28815276064).jpg", description:"The National September 11 Memorial & Museum is a memorial and museum in New York City commemorating the September 11, 2001 attacks, which killed 2,977 people, and the 1993 World Trade Center bombing, which killed six"},
 {name:"One World Trade Center",image_url:"https://en.wikipedia.org/wiki/One_World_Trade_Center#/media/File:New_York_(33224081040).jpg", description:"One World Trade Center is the main building of the rebuilt World Trade Center complex in Lower Manhattan, New York City. One WTC is the tallest building in the United States, the tallest building in the Western Hemisphere, and the seventh-tallest in the world."},
 {name:"Federal Hall",image_url:"https://en.wikipedia.org/wiki/Federal_Hall#/media/File:Federal_Hall_(48126566178).jpg", description:"Federal Hall is a historic building at 26 Wall Street in the Financial District of Manhattan in New York City. The name originally referred to a Federal style building on the same site, completed in 1703 as City Hall."},
 {name:"South Street Seaport Museum",image_url:"https://en.wikipedia.org/wiki/South_Street_Seaport#/media/File:US_Navy_050529-N-7676W-006_ONR_Afloat_Lab_YP-679_Starfish_at_South_Street_Seaport_Pier_17_during_18th_annual_Fleet_Week_New_York.jpg", description:"Institution housing paintings, ship models, scrimshaw & more with vintage ships docked outside."},
 {name:"Charging Bull",image_url:" https://en.wikipedia.org/wiki/Charging_Bull#/media/File:Charging_Bull_statue.jpg", description:"Charging Bull, sometimes referred to as the Bull of Wall Street or the Bowling Green Bull, is a bronze sculpture that stands on Broadway just north of Bowling Green in the Financial District of Manhattan in New York City"},
 {name:"Museum of the American Indian",image_url:"https://en.wikipedia.org/wiki/National_Museum_of_the_American_Indian#/media/File:National_Museum_of_the_American_Indian,_New_York_11.jpg", description:"Native American art & artifacts, some going back 12,000 years, displayed in a former customs house."},
 {name:"Bowling Green Park",image_url:"https://en.wikipedia.org/wiki/Bowling_Green_(New_York_City)#/media/File:Bowling_Green_Fence_and_Park_01.jpg", description:"Bowling Green is a small public park in the Financial District of Lower Manhattan, New York City, at the southern end of Broadway. Located next to the site of the original Dutch fort of New Amsterdam, it served as a public place before being designated as a park in 1733"},
 {name:"Pier 15, East River Esplanade",image_url:"https://archidose.blogspot.com/2012/01/pier-15.html", description:"Public pier with a 2-story structure for picnics & basking beside the river, plus a bar/cafe."},
 {name:"The Statue of Liberty",image_url:"https://en.wikipedia.org/wiki/Statue_of_Liberty#/media/File:Lady_Liberty_under_a_blue_sky_(cropped).jpg", description:"The Statue of Liberty Enlightening the World was a gift of friendship from the people of France to the United States and is recognized as a universal symbol of freedom and democracy"},
 {name:"National September 11 Memorial",image_url:"https://en.wikipedia.org/wiki/National_September_11_Memorial_%26_Museum#/media/File:9-11_Memorial_and_Museum_(28815276064).jpg", description:"The National September 11 Memorial & Museum is a memorial and museum in New York City commemorating the September 11, 2001 attacks, which killed 2,977 people, and the 1993 World Trade Center bombing, which killed six"},
 {name:"One World Trade Center",image_url:"https://en.wikipedia.org/wiki/One_World_Trade_Center#/media/File:New_York_(33224081040).jpg", description:"One World Trade Center is the main building of the rebuilt World Trade Center complex in Lower Manhattan, New York City. One WTC is the tallest building in the United States, the tallest building in the Western Hemisphere, and the seventh-tallest in the world."},
 {name:"Federal Hall",image_url:"https://en.wikipedia.org/wiki/Federal_Hall#/media/File:Federal_Hall_(48126566178).jpg", description:"Federal Hall is a historic building at 26 Wall Street in the Financial District of Manhattan in New York City. The name originally referred to a Federal style building on the same site, completed in 1703 as City Hall."},
 {name:"South Street Seaport Museum",image_url:"https://en.wikipedia.org/wiki/South_Street_Seaport#/media/File:US_Navy_050529-N-7676W-006_ONR_Afloat_Lab_YP-679_Starfish_at_South_Street_Seaport_Pier_17_during_18th_annual_Fleet_Week_New_York.jpg", description:"Institution housing paintings, ship models, scrimshaw & more with vintage ships docked outside."},
 {name:"Charging Bull",image_url:" https://en.wikipedia.org/wiki/Charging_Bull#/media/File:Charging_Bull_statue.jpg", description:"Charging Bull, sometimes referred to as the Bull of Wall Street or the Bowling Green Bull, is a bronze sculpture that stands on Broadway just north of Bowling Green in the Financial District of Manhattan in New York City"},
 {name:"Museum of the American Indian",image_url:"https://en.wikipedia.org/wiki/National_Museum_of_the_American_Indian#/media/File:National_Museum_of_the_American_Indian,_New_York_11.jpg", description:"Native American art & artifacts, some going back 12,000 years, displayed in a former customs house."},
 {name:"Bowling Green Park",image_url:"https://en.wikipedia.org/wiki/Bowling_Green_(New_York_City)#/media/File:Bowling_Green_Fence_and_Park_01.jpg", description:"Bowling Green is a small public park in the Financial District of Lower Manhattan, New York City, at the southern end of Broadway. Located next to the site of the original Dutch fort of New Amsterdam, it served as a public place before being designated as a park in 1733"},
 {name:"Pier 15, East River Esplanade",image_url:"https://archidose.blogspot.com/2012/01/pier-15.html", description:"Public pier with a 2-story structure for picnics & basking beside the river, plus a bar/cafe."},
 {name:"The Statue of Liberty",image_url:"https://en.wikipedia.org/wiki/Statue_of_Liberty#/media/File:Lady_Liberty_under_a_blue_sky_(cropped).jpg", description:"The Statue of Liberty Enlightening the World was a gift of friendship from the people of France to the United States and is recognized as a universal symbol of freedom and democracy"},
 {name:"National September 11 Memorial",image_url:"https://en.wikipedia.org/wiki/National_September_11_Memorial_%26_Museum#/media/File:9-11_Memorial_and_Museum_(28815276064).jpg", description:"The National September 11 Memorial & Museum is a memorial and museum in New York City commemorating the September 11, 2001 attacks, which killed 2,977 people, and the 1993 World Trade Center bombing, which killed six"},
 {name:"One World Trade Center",image_url:"https://en.wikipedia.org/wiki/One_World_Trade_Center#/media/File:New_York_(33224081040).jpg", description:"One World Trade Center is the main building of the rebuilt World Trade Center complex in Lower Manhattan, New York City. One WTC is the tallest building in the United States, the tallest building in the Western Hemisphere, and the seventh-tallest in the world."},
 {name:"Federal Hall",image_url:"https://en.wikipedia.org/wiki/Federal_Hall#/media/File:Federal_Hall_(48126566178).jpg", description:"Federal Hall is a historic building at 26 Wall Street in the Financial District of Manhattan in New York City. The name originally referred to a Federal style building on the same site, completed in 1703 as City Hall."}
 
];



//San Fran  Activities by location
export const soMa = [
  {name:"Yerba Buena Gardens", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/s2dGrcHrr4bXKi_XxqpKMQ/o.jpg",description:"Landscaped green space, great food, museums and culture, ice skating and bowling, public art, shopping -- all in the heart of DWTN SF."},
{name:"The View Lounge", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rxcBoPUlApxeF3nwCYx9nQ/o.jpg",description:"Come relax and take in the breath taking views of the city."},
{name:"San Francisco Museum of Modern Art", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/igdi2NkR0P-3S4FCX39FmQ/o.jpg",description:"The acclaimed SF MoMa."},
{name:"Bottom of the Hill", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/SbpkaDiogsWT8N2Tda3pPw/o.jpg",description:"SoMa's favorite Music Venue"},
{name:"SPiN - San Francisco", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-lLrLBft-YC-uU8EGOjhkA/o.jpg",description:"Cocktails and Ping Pong!"},
{name:"Wreck It Yourself", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/lL8y4Yj2L6h_i8J66MG8PA/o.jpg",description:"Wreck Room. It's okay to be mad! book your next date or therapy session with us while having fun!"},
{name:"Yerba Buena Ice Skating & Bowling Center", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/Z9frVlFHdHms4a10fZeDCQ/o.jpg",description:"Bowling & Ice Skating in Yerba Buena Gardens."},
{name:"Reason", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/JDmlaubAEP2IoQTt__Wg-g/o.jpg",description:"World-class sci-fi escape room for remote teams from anywhere or in-person teams in SF. Experience high-tech team-building with 3D Printing, holograms, AI, Blockchain, robotics, and more."},
{name:"KAIYŌ Rooftop", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/xg4DGzFWQzM5fK_PcHQVJA/o.jpg",description:"Kaiyo Rooftop is a tropical oasis in the sky, an immersive Nikkei experience that transports guests the moment they walk through the elevator door. Plants, rich textiles, colorful fabrics, soft lighting and stunning food/cocktails invite guests to explore the Japanese culinary influence within Peruvian culture."},
{name:"Yerba Buena Gardens", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/s2dGrcHrr4bXKi_XxqpKMQ/o.jpg",description:"Landscaped green space, great food, museums and culture, ice skating and bowling, public art, shopping -- all in the heart of DWTN SF."},
{name:"The View Lounge", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rxcBoPUlApxeF3nwCYx9nQ/o.jpg",description:"Come relax and take in the breath taking views of the city."},
{name:"San Francisco Museum of Modern Art", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/igdi2NkR0P-3S4FCX39FmQ/o.jpg",description:"The acclaimed SF MoMa."},
{name:"Bottom of the Hill", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/SbpkaDiogsWT8N2Tda3pPw/o.jpg",description:"SoMa's favorite Music Venue"},
{name:"SPiN - San Francisco", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-lLrLBft-YC-uU8EGOjhkA/o.jpg",description:"Cocktails and Ping Pong!"},
{name:"Wreck It Yourself", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/lL8y4Yj2L6h_i8J66MG8PA/o.jpg",description:"Wreck Room. It's okay to be mad! book your next date or therapy session with us while having fun!"},
{name:"Yerba Buena Ice Skating & Bowling Center", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/Z9frVlFHdHms4a10fZeDCQ/o.jpg",description:"Bowling & Ice Skating in Yerba Buena Gardens."},
{name:"Reason", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/JDmlaubAEP2IoQTt__Wg-g/o.jpg",description:"World-class sci-fi escape room for remote teams from anywhere or in-person teams in SF. Experience high-tech team-building with 3D Printing, holograms, AI, Blockchain, robotics, and more."},
{name:"KAIYŌ Rooftop", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/xg4DGzFWQzM5fK_PcHQVJA/o.jpg",description:"Kaiyo Rooftop is a tropical oasis in the sky, an immersive Nikkei experience that transports guests the moment they walk through the elevator door. Plants, rich textiles, colorful fabrics, soft lighting and stunning food/cocktails invite guests to explore the Japanese culinary influence within Peruvian culture."},
{name:"Yerba Buena Gardens", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/s2dGrcHrr4bXKi_XxqpKMQ/o.jpg",description:"Landscaped green space, great food, museums and culture, ice skating and bowling, public art, shopping -- all in the heart of DWTN SF."},
{name:"The View Lounge", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rxcBoPUlApxeF3nwCYx9nQ/o.jpg",description:"Come relax and take in the breath taking views of the city."},
{name:"San Francisco Museum of Modern Art", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/igdi2NkR0P-3S4FCX39FmQ/o.jpg",description:"The acclaimed SF MoMa."},
{name:"Bottom of the Hill", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/SbpkaDiogsWT8N2Tda3pPw/o.jpg",description:"SoMa's favorite Music Venue"}
] ;

export const upperHaight = [
  {name:"Conservatory of Flowers", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/8qEFV9DUyBAN1lwNzLpZMA/o.jpg",description:"The Conservatory of Flowers is a unique living museum that's bursting with life just waiting to be discovered. Its intimate setting gives visitors an up-close look at rare, exotic plants and beautiful tropical flowers."},
{name:"The Independent", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/Rv3HoRyVjZg3UYhsurXj-w/o.jpg",description:"Come relax and take in the breath taking views of the city."},
{name:"The Castro Theatre", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/XKNnaMKKy3dKgIHiLoLK7w/o.jpg",description:"Historic venue. Film and live comedy in the nearbay Castro District"},
{name:"California Academy of Sciences", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/7eCeoH7kp3h3GAek7UCmvQ/o.jpg",description:"Science museum with a stunning indoor rainforest, aquarium, and state-of-the-art planetarium"},
{name:"de Young", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/QU6UQqGqBiBeIro7A4Sa8g/o.jpg",description:"Acclaimed art museum, houses collections of American painting, sculpture, and decorative arts from the 17th to the 21st centuries; art from Oceania, Africa, and the Americas; a diverse collection of costumes and textiles; and international contemporary art"},
{name:"Seward Mini Park", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-tUzm-QqHJ7H2t_gyWSOrQ/o.jpg",description:"Seward Street Slides are two super steep concrete slides located in Seward Mini Park (built in 1973) and they were designed by a 14-year-old girl Kim Clark who won the design competition put on by sculptor Ruth Asawa."},
{name:"Church of 8 Wheels", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/8femhSNNLVgHcUsbdcH3xQ/o.jpg",description:"Former Catholic Church converted to an unparalleled Roller Disco Experience!"},
{name:"Hawthorn", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rQYyplWnft93SY1Bhp2CVQ/o.jpg",description:"It's no secret, San Franciscans like a good cocktail & great music. With that in mind, welcome to Hawthorn, a SF hybrid cocktail lounge for mature individuals seeking intelligent nightlife."},
{name:"Emporium San Francisco", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rrlmyXOhC3fpjsOvid2yyQ/o.jpg",description:"Arcade bar & venue inside the Harding Theater, a 100 year old historic San Francisco venue. We offer the largest selection of arcade games, pinball, pool, air hockey, shuffleboard, skee ball, super chexx, foosball, as well as live DJs, a movie screen, and full stage with live musical performances."},
{name:"Conservatory of Flowers", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/8qEFV9DUyBAN1lwNzLpZMA/o.jpg",description:"The Conservatory of Flowers is a unique living museum that's bursting with life just waiting to be discovered. Its intimate setting gives visitors an up-close look at rare, exotic plants and beautiful tropical flowers."},
{name:"The Independent", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/Rv3HoRyVjZg3UYhsurXj-w/o.jpg",description:"Come relax and take in the breath taking views of the city."},
{name:"The Castro Theatre", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/XKNnaMKKy3dKgIHiLoLK7w/o.jpg",description:"Historic venue. Film and live comedy in the nearbay Castro District"},
{name:"California Academy of Sciences", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/7eCeoH7kp3h3GAek7UCmvQ/o.jpg",description:"Science museum with a stunning indoor rainforest, aquarium, and state-of-the-art planetarium"},
{name:"de Young", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/QU6UQqGqBiBeIro7A4Sa8g/o.jpg",description:"Acclaimed art museum, houses collections of American painting, sculpture, and decorative arts from the 17th to the 21st centuries; art from Oceania, Africa, and the Americas; a diverse collection of costumes and textiles; and international contemporary art"},
{name:"Seward Mini Park", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-tUzm-QqHJ7H2t_gyWSOrQ/o.jpg",description:"Seward Street Slides are two super steep concrete slides located in Seward Mini Park (built in 1973) and they were designed by a 14-year-old girl Kim Clark who won the design competition put on by sculptor Ruth Asawa."},
{name:"Church of 8 Wheels", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/8femhSNNLVgHcUsbdcH3xQ/o.jpg",description:"Former Catholic Church converted to an unparalleled Roller Disco Experience!"},
{name:"Hawthorn", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rQYyplWnft93SY1Bhp2CVQ/o.jpg",description:"It's no secret, San Franciscans like a good cocktail & great music. With that in mind, welcome to Hawthorn, a SF hybrid cocktail lounge for mature individuals seeking intelligent nightlife."},
{name:"Emporium San Francisco", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/rrlmyXOhC3fpjsOvid2yyQ/o.jpg",description:"Arcade bar & venue inside the Harding Theater, a 100 year old historic San Francisco venue. We offer the largest selection of arcade games, pinball, pool, air hockey, shuffleboard, skee ball, super chexx, foosball, as well as live DJs, a movie screen, and full stage with live musical performances."},
{name:"Conservatory of Flowers", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/8qEFV9DUyBAN1lwNzLpZMA/o.jpg",description:"The Conservatory of Flowers is a unique living museum that's bursting with life just waiting to be discovered. Its intimate setting gives visitors an up-close look at rare, exotic plants and beautiful tropical flowers."},
{name:"The Independent", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/Rv3HoRyVjZg3UYhsurXj-w/o.jpg",description:"Come relax and take in the breath taking views of the city."},
{name:"The Castro Theatre", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/XKNnaMKKy3dKgIHiLoLK7w/o.jpg",description:"Historic venue. Film and live comedy in the nearbay Castro District"}

] ;

 export const missionDistrict = [
  {name:"Arcana", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/6HxYbMHRvL5SEsDhTwTfwQ/o.jpg",description:"An urban greenhouse, a shared `living room` in the heart of Mission. At Arcana, magical mysteries come together to celebrate nature, culture, music and art from all over the world. Bar, Restaurant and Entertainment Serving global natural wines and plant-based food inspired by Middle Eastern cuisine."},
{name:"Mission Cultural Center For Latino Arts", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/6ktNcWXyUM8UUjp6v4LBfg/o.jpg",description:"Art school, dance studio, and cultural center serving the Mission."},
{name:"The Chapel", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-mzzqbTUgGKKGLMmG4NrPA/o.jpg",description:"The Chapel is a music venue in the heart of San Francisco's Mission District. In addition to live shows in the venue, the Main Bar is also a great place for concert ticket-holders to enjoy specialty cocktails and food before, during and after shows."},
{name:"Radio Habana Social Club", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/2GsfzQu9fOtwVuz4IBNSNg/o.jpg",description:"A San Francisco institution. Bar featuring live (big band and acoustic) and dj music, film and art showings, comedy, drag, spoken word, jams, burlesque and fundraisers to no end."},
{name:"Mission Dolores Park", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/sG7kqe_sN5med9j7c7U_vg/o.jpg",description:"A popular picnic spot for locals, surrounded by breathtaking panoramic views of the City."},
{name:"Film Nights In The Park", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/FSCkfRPVINgrH16BwRfIkQ/o.jpg",description:"What better way to spend a Saturday night than watching a movie outdoors on a warm blanket, surrounded by friends, pizza, wine and beautiful views of San Francisco?"},
{name:"Alamo Drafthouse Cinema New Mission", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/SBamJryJh3Ui49cuTckCIw/o.jpg",description:"The Alamo Drafthouse Theater is good food, good beer and good film, all at the same place! "},
{name:"Adventures In Clay", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/ILWa2NNkTy47j1GkEjPsuA/o.jpg",description:"Intimate pottery classes in the Mission."},
{name:"Adventurous Sports-Endless Slope", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/UNWZpGuGx5WDg_p_wM9A9Q/o.jpg",description:"The Endless Slope is Accelerated Learning for snowboarding and skiing. All lessons are private, indoors, and completely customized for your fitness, learning style and goals."},
{name:"Arcana", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/6HxYbMHRvL5SEsDhTwTfwQ/o.jpg",description:"An urban greenhouse, a shared `living room` in the heart of Mission. At Arcana, magical mysteries come together to celebrate nature, culture, music and art from all over the world. Bar, Restaurant and Entertainment Serving global natural wines and plant-based food inspired by Middle Eastern cuisine."},
{name:"Mission Cultural Center For Latino Arts", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/6ktNcWXyUM8UUjp6v4LBfg/o.jpg",description:"Art school, dance studio, and cultural center serving the Mission."},
{name:"The Chapel", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-mzzqbTUgGKKGLMmG4NrPA/o.jpg",description:"The Chapel is a music venue in the heart of San Francisco's Mission District. In addition to live shows in the venue, the Main Bar is also a great place for concert ticket-holders to enjoy specialty cocktails and food before, during and after shows."},
{name:"Radio Habana Social Club", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/2GsfzQu9fOtwVuz4IBNSNg/o.jpg",description:"A San Francisco institution. Bar featuring live (big band and acoustic) and dj music, film and art showings, comedy, drag, spoken word, jams, burlesque and fundraisers to no end."},
{name:"Mission Dolores Park", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/sG7kqe_sN5med9j7c7U_vg/o.jpg",description:"A popular picnic spot for locals, surrounded by breathtaking panoramic views of the City."},
{name:"Film Nights In The Park", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/FSCkfRPVINgrH16BwRfIkQ/o.jpg",description:"What better way to spend a Saturday night than watching a movie outdoors on a warm blanket, surrounded by friends, pizza, wine and beautiful views of San Francisco?"},
{name:"Alamo Drafthouse Cinema New Mission", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/SBamJryJh3Ui49cuTckCIw/o.jpg",description:"The Alamo Drafthouse Theater is good food, good beer and good film, all at the same place! "},
{name:"Adventures In Clay", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/ILWa2NNkTy47j1GkEjPsuA/o.jpg",description:"Intimate pottery classes in the Mission."},
{name:"Adventurous Sports-Endless Slope", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/UNWZpGuGx5WDg_p_wM9A9Q/o.jpg",description:"The Endless Slope is Accelerated Learning for snowboarding and skiing. All lessons are private, indoors, and completely customized for your fitness, learning style and goals."},
{name:"Arcana", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/6HxYbMHRvL5SEsDhTwTfwQ/o.jpg",description:"An urban greenhouse, a shared `living room` in the heart of Mission. At Arcana, magical mysteries come together to celebrate nature, culture, music and art from all over the world. Bar, Restaurant and Entertainment Serving global natural wines and plant-based food inspired by Middle Eastern cuisine."},
{name:"Mission Cultural Center For Latino Arts", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/6ktNcWXyUM8UUjp6v4LBfg/o.jpg",description:"Art school, dance studio, and cultural center serving the Mission."},
{name:"The Chapel", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/-mzzqbTUgGKKGLMmG4NrPA/o.jpg",description:"The Chapel is a music venue in the heart of San Francisco's Mission District. In addition to live shows in the venue, the Main Bar is also a great place for concert ticket-holders to enjoy specialty cocktails and food before, during and after shows."}

] ;

export const theMarina = [
  {name:"Japantown", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/XcwWEbED6X_0BykmSPc7sA/o.jpg",description:"San Francisco's Japantown has been the center of the Bay Area's Japanese and Japanese American community since 1906. It continues to an exciting place to explore and find authentic Japanese culture, restaurants and shops."},
{name:"Palace of Fine Arts", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/D3XLMNyAg61WzZtw_nco4A/o.jpg",description:"Greco-Roman interiors and lush landscaping next to Golden Gate Bridge. Originally built for the 1915 Panama-Pacific Exhibition, it houses an enormous exhibition center and theater, and is surrounded by a stunning lagoon."},
{name:"The Walt Disney Family Museum", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/0zaWkFJLRv3CiRSzrZENcA/o.jpg",description:"The Walt Disney Family Museum tells the story of the life and work of Walt Disney."},
{name:"PIER 39", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/5tMxcoc0x2mAIZG9A2JUAA/o.jpg",description:"PIER 39 is the premiere entertainment destination in the heart of the San Francisco waterfront."},
{name:"Cobb's Comedy Club", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/e9Ak1sOp35TOOyzmzTBo3w/o.jpg",description:" Located in San Francisco's nearby famous North Beach, Cobb's offers a taste of old San Francisco and the city's ever-changing nightlife."},
{name:"GoCar Tours", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/9OHhDL4Tg50aqEjua8bfVw/o.jpg",description:"It's a tour guide...a talking car...a trusty co-pilot...and a local on wheels. GoCar is the first-ever     GPS-guided storytelling car - and it's available to rent right now!"},
{name:"House of Air", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/_MddmEjVt17eP9CySxTNbw/o.jpg",description:"House of Air offers open trampoline park jump access, trampoline aerial training for all types of disciplines (board sports, gymnasts, divers, core fitness), morning workout / fitness classes, boot camp, and trampoline dodgeball."},
{name:"Palace Games", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/LQJRdAXlpyfY5Tdtul-Tkg/o.jpg",description:"Creators of The Great Houdini Escape Room, The Roosevelt Escape Room, The Edison Escape Room, and Escape the Palace at the Palace of Fine Arts! Palace Games develops unique games and immersive experiences designed for team building / company offsites, fun with friends, birthday celebrations, parties or other special occasions."},
{name:"Exploratorium After Dark", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/awiL8kFlWfX8AuCaGWG7Mg/o.jpg",description:"Things look different after dark. Lose yourself in more than 600 interactive exhibits in spacious galleries exploring perception, art, and science. Grab your friends and a drink and get immersed in everything from a fog bridge to a large-scale kaleidoscope, dazzling light displays, mind-bending mirrors, and more."},
{name:"Japantown", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/XcwWEbED6X_0BykmSPc7sA/o.jpg",description:"San Francisco's Japantown has been the center of the Bay Area's Japanese and Japanese American community since 1906. It continues to an exciting place to explore and find authentic Japanese culture, restaurants and shops."},
{name:"Palace of Fine Arts", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/D3XLMNyAg61WzZtw_nco4A/o.jpg",description:"Greco-Roman interiors and lush landscaping next to Golden Gate Bridge. Originally built for the 1915 Panama-Pacific Exhibition, it houses an enormous exhibition center and theater, and is surrounded by a stunning lagoon."},
{name:"The Walt Disney Family Museum", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/0zaWkFJLRv3CiRSzrZENcA/o.jpg",description:"The Walt Disney Family Museum tells the story of the life and work of Walt Disney."},
{name:"PIER 39", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/5tMxcoc0x2mAIZG9A2JUAA/o.jpg",description:"PIER 39 is the premiere entertainment destination in the heart of the San Francisco waterfront."},
{name:"Cobb's Comedy Club", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/e9Ak1sOp35TOOyzmzTBo3w/o.jpg",description:" Located in San Francisco's nearby famous North Beach, Cobb's offers a taste of old San Francisco and the city's ever-changing nightlife."},
{name:"GoCar Tours", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/9OHhDL4Tg50aqEjua8bfVw/o.jpg",description:"It's a tour guide...a talking car...a trusty co-pilot...and a local on wheels. GoCar is the first-ever     GPS-guided storytelling car - and it's available to rent right now!"},
{name:"House of Air", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/_MddmEjVt17eP9CySxTNbw/o.jpg",description:"House of Air offers open trampoline park jump access, trampoline aerial training for all types of disciplines (board sports, gymnasts, divers, core fitness), morning workout / fitness classes, boot camp, and trampoline dodgeball."},
{name:"Palace Games", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/LQJRdAXlpyfY5Tdtul-Tkg/o.jpg",description:"Creators of The Great Houdini Escape Room, The Roosevelt Escape Room, The Edison Escape Room, and Escape the Palace at the Palace of Fine Arts! Palace Games develops unique games and immersive experiences designed for team building / company offsites, fun with friends, birthday celebrations, parties or other special occasions."},
{name:"Exploratorium After Dark", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/awiL8kFlWfX8AuCaGWG7Mg/o.jpg",description:"Things look different after dark. Lose yourself in more than 600 interactive exhibits in spacious galleries exploring perception, art, and science. Grab your friends and a drink and get immersed in everything from a fog bridge to a large-scale kaleidoscope, dazzling light displays, mind-bending mirrors, and more."},
{name:"Japantown", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/XcwWEbED6X_0BykmSPc7sA/o.jpg",description:"San Francisco's Japantown has been the center of the Bay Area's Japanese and Japanese American community since 1906. It continues to an exciting place to explore and find authentic Japanese culture, restaurants and shops."},
{name:"Palace of Fine Arts", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/D3XLMNyAg61WzZtw_nco4A/o.jpg",description:"Greco-Roman interiors and lush landscaping next to Golden Gate Bridge. Originally built for the 1915 Panama-Pacific Exhibition, it houses an enormous exhibition center and theater, and is surrounded by a stunning lagoon."},
{name:"The Walt Disney Family Museum", image_url:"https://s3-media0.fl.yelpcdn.com/bphoto/0zaWkFJLRv3CiRSzrZENcA/o.jpg",description:"The Walt Disney Family Museum tells the story of the life and work of Walt Disney."}

] ;




