"""empty message

Revision ID: 0e2757f794ca
Revises: 28a1b0d94925
Create Date: 2022-07-04 05:57:45.458047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e2757f794ca'
down_revision = '28a1b0d94925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dinner', sa.Integer(), nullable=True),
    sa.Column('dessert', sa.Integer(), nullable=True),
    sa.Column('dateName', sa.String(length=200), nullable=True),
    sa.Column('dateImg', sa.String(length=200), nullable=True),
    sa.Column('dateDes', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upComing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dinner', sa.Integer(), nullable=True),
    sa.Column('dessert', sa.Integer(), nullable=True),
    sa.Column('dateName', sa.String(length=200), nullable=True),
    sa.Column('dateImg', sa.String(length=200), nullable=True),
    sa.Column('dateDes', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upComing')
    op.drop_table('desires')
    # ### end Alembic commands ###
