"""empty message

Revision ID: 20000698953d
Revises: a22ceca47748
Create Date: 2022-07-06 06:58:03.220745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20000698953d'
down_revision = 'a22ceca47748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dessert', sa.Column('dessert', sa.String(length=120), nullable=True))
    op.add_column('dessert', sa.Column('desImg', sa.String(length=200), nullable=True))
    op.add_column('dessert', sa.Column('desLoc', sa.String(length=200), nullable=True))
    op.add_column('dessert', sa.Column('desRating', sa.String(length=200), nullable=True))
    op.drop_column('dessert', 'location')
    op.drop_column('dessert', 'image3')
    op.drop_column('dessert', 'title')
    op.drop_column('dessert', 'image1')
    op.drop_column('dessert', 'image2')
    op.drop_column('dessert', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dessert', sa.Column('time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('dessert', sa.Column('image2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('dessert', sa.Column('image1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('dessert', sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('dessert', sa.Column('image3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('dessert', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('dessert', 'desRating')
    op.drop_column('dessert', 'desLoc')
    op.drop_column('dessert', 'desImg')
    op.drop_column('dessert', 'dessert')
    # ### end Alembic commands ###
