"""empty message

Revision ID: 28a1b0d94925
Revises: 839710328a23
Create Date: 2022-06-02 16:30:36.955979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28a1b0d94925'
down_revision = '839710328a23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dessert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('image1', sa.String(length=200), nullable=True),
    sa.Column('image2', sa.String(length=200), nullable=True),
    sa.Column('image3', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dinner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('image1', sa.String(length=200), nullable=True),
    sa.Column('image2', sa.String(length=200), nullable=True),
    sa.Column('image3', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fridate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('image1', sa.String(length=200), nullable=True),
    sa.Column('image2', sa.String(length=200), nullable=True),
    sa.Column('image3', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fridate')
    op.drop_table('dinner')
    op.drop_table('dessert')
    # ### end Alembic commands ###
