"""empty message

Revision ID: 39c236b7f781
Revises: 516de346493f
Create Date: 2022-07-06 05:35:38.562281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c236b7f781'
down_revision = '516de346493f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('desires', sa.Column('dinImg', sa.String(length=200), nullable=True))
    op.add_column('desires', sa.Column('dinLoc', sa.String(length=200), nullable=True))
    op.add_column('desires', sa.Column('desImg', sa.String(length=200), nullable=True))
    op.add_column('desires', sa.Column('desLoc', sa.String(length=200), nullable=True))
    op.add_column('memories', sa.Column('dinImg', sa.String(length=200), nullable=True))
    op.add_column('memories', sa.Column('dinLoc', sa.String(length=200), nullable=True))
    op.add_column('memories', sa.Column('desImg', sa.String(length=200), nullable=True))
    op.add_column('memories', sa.Column('desLoc', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'desLoc')
    op.drop_column('memories', 'desImg')
    op.drop_column('memories', 'dinLoc')
    op.drop_column('memories', 'dinImg')
    op.drop_column('desires', 'desLoc')
    op.drop_column('desires', 'desImg')
    op.drop_column('desires', 'dinLoc')
    op.drop_column('desires', 'dinImg')
    # ### end Alembic commands ###
