"""empty message

Revision ID: 39feb1bb384a
Revises: 55cb276b67d4
Create Date: 2022-07-04 19:47:57.423146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39feb1bb384a'
down_revision = '55cb276b67d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('desires', 'dinner',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('desires', 'dessert',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('memories', 'dinner',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('memories', 'dessert',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('upComing', 'dinner',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('upComing', 'dessert',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upComing', 'dessert',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('upComing', 'dinner',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('memories', 'dessert',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('memories', 'dinner',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('desires', 'dessert',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('desires', 'dinner',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
