"""empty message

Revision ID: 6016645562ac
Revises: 20000698953d
Create Date: 2022-07-07 05:03:02.494510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6016645562ac'
down_revision = '20000698953d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.Column('dateImg', sa.String(length=200), nullable=True),
    sa.Column('dateDes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date')
    # ### end Alembic commands ###
