"""empty message

Revision ID: 9d3461145c2f
Revises: c555ad515c7c
Create Date: 2022-07-04 22:28:34.282338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3461145c2f'
down_revision = 'c555ad515c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upcoming', sa.Column('dinImg', sa.String(length=200), nullable=True))
    op.add_column('upcoming', sa.Column('dinLoc', sa.String(length=200), nullable=True))
    op.add_column('upcoming', sa.Column('desImg', sa.String(length=200), nullable=True))
    op.add_column('upcoming', sa.Column('desLoc', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upcoming', 'desLoc')
    op.drop_column('upcoming', 'desImg')
    op.drop_column('upcoming', 'dinLoc')
    op.drop_column('upcoming', 'dinImg')
    # ### end Alembic commands ###
