"""empty message

Revision ID: a22ceca47748
Revises: 39c236b7f781
Create Date: 2022-07-06 06:24:11.997557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22ceca47748'
down_revision = '39c236b7f781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinner', sa.Column('dinner', sa.String(length=120), nullable=True))
    op.add_column('dinner', sa.Column('dinImg', sa.String(length=200), nullable=True))
    op.add_column('dinner', sa.Column('dinLoc', sa.String(length=200), nullable=True))
    op.add_column('dinner', sa.Column('dinRating', sa.String(length=200), nullable=True))
    op.drop_column('dinner', 'image2')
    op.drop_column('dinner', 'title')
    op.drop_column('dinner', 'location')
    op.drop_column('dinner', 'time')
    op.drop_column('dinner', 'image3')
    op.drop_column('dinner', 'image1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dinner', sa.Column('image1', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('dinner', sa.Column('image3', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('dinner', sa.Column('time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('dinner', sa.Column('location', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('dinner', sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('dinner', sa.Column('image2', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('dinner', 'dinRating')
    op.drop_column('dinner', 'dinLoc')
    op.drop_column('dinner', 'dinImg')
    op.drop_column('dinner', 'dinner')
    # ### end Alembic commands ###
